# Generated by Django 4.1 on 2022-08-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
