# Generated by Django 4.1 on 2022-08-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_published_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Liked'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m', verbose_name='Video'),
        ),
    ]
